---
title: "psych.251.reproducibility"
author: "kris evans"
date: "10/22/2020"
output: html_document
---
#### Packages ####
```{r}


library(data.table)
library(plyr)
library(ggplot2)
library(multilevel)
library(lme4)
library(lmSupport)
library(AICcmodavg)
library(pbkrtest)
library(boot)
library(haven)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#setwd
#https://midus.colectica.org// general data repository good to see all the time points data and variables

load("/Users/krise/R Mac working folder/sommerfeldt2019/ICPSR_29282/DS0001/29282-0001-Data.rda") #bio data
load("/Users/krise/R Mac working folder/sommerfeldt2019/ICPSR_04652/DS0001/04652-0001-Data.rda") #M2 survey 
load("/Users/krise/R Mac working folder/sommerfeldt2019/ICPSR_22840/DS0001/22840-0001-Data-REST.rda") #Milwaukee 
load("/Users/krise/R Mac working folder/sommerfeldt2019/ICPSR_02760/DS0001/02760-0001-Data.rda") #M1 


#upload and save data  - data prep github - https://github.com/sashasomms/coherence_behavioral/blob/master/Prep_Coherence_MIDUSII_20180727.R
#original repo - https://github.com/sashasomms/coherence_behavioral/

#Project 4 MIDUS 2 - Biomarkers data RAW data upload and save as framework - https://www.icpsr.umich.edu/web/ICPSR/studies%20/29282#
#downloaded straight to R using .rda file and will output #need to confirm this is right data set as there are other data files here (DS0001 and DS0002) bsed on the original data upload looks like it is the DS001 data, we downloaded the R version of the data .rda


bio.d <- da29282.0001


 #Project 1- (MIDUS 2) - Look s like this is MIDUS2 part 1, not MIDUS 1 Survey-   RAW data upload and save as framework - https://www.icpsr.umich.edu/web/ICPSR/studies%20/04652#
#raw data sets offer multiple versions will take most similar path of primary data set as opposed to all of them but may need to return to retrieve them ##likely the MIDUS 04-06 midus 2

sur.d <- da04652.0001



#Project 1- (MIDUS 2)  Milwaukee African American Sample - need special permission - https://www.icpsr.umich.edu/web/NACDA/studies/22840

mil.d <- da22840.0001

#saveoutput data to easily retrieve


#MIDUS 1 p1 # Zygosity data from Midus I https://midus.colectica.org/
# Downloaded from colectica with variables: M2ID, ZYGCAT, TOT_SIBS  --not sure if downloaded whole data set or just these variables, looks like M2ID and TOT_SIBS are in the M1 sturvey but ZYGCAT is twin survey data, a different cohort.

m1.d <- da02760.0001



#saveoutput data to easily retrieve 
write.csv(bio.d,"r.bio.d.csv")

#saveoutput data to easily retrieve
write.csv(sur.d, "r.sur.d.csv")

#saveoutput data to easily retrieve
write.csv(m1.d,"r.m1.sur.d.csv")




```


```{r}
#load data from personal dir
#### Read in Data #### helpful to view variables here too bio- https://midus.colectica.org/data/int.example/791f12ac-b75b-4ab2-a07c-887d20ca35ca/int.example/11f11291-99c9-4861-9008-eafe34544fc1/int.example/b595aa35-77cc-47b7-89a4-ed1dece9ec6b
# Project 4 (biomarker)

dfP4 = bio.d ##read in new data here, make similar to old processing names for ease #biomarker data M2P4
dfP1 = sur.d ##4652
dfP1M = mil.d #milwaukee data 22840
dfPZ = m1.d


names(dfP4)
summary(dfP4$SAMPLMAJ) #matches the data check from the codebook 29282
length(dfP4$M2ID) #matches the data check 1255



names(dfP1)
summary(dfP1$SAMPLMAJ) #matches the codebook data
length(dfP1$M2ID) #matches codebook data 4652

summary(dfP1M$BACRSEX) #matches the milwaukee data set 22840
length(dfP1M$M2ID) #matches, there is no SAMPLMAJ var


length(dfPZ$M2ID) #matches codebook for the M1 data 2760
```

```{r}

####################################################
#### Clean & organize Project 4 (Biomarker) data ####
#####################################################
## Self reports of stress -- this is stress rating, baseline 
stressSRO = c('B4VSRB1', 'B4VSRCS1', 'B4VSRR1', 'B4VSRCS2', 'B4VSRR2', 'B4VSRU1') # old names --
stressSR = c('stress1', 'stress2', 'stress3', 'stress4', 'stress5', 'stress6') # new names


## Heart rate
ecg_HRO = c('B4VB1HR', 'B4VM1HR', 'B4VR1HR', 'B4VS1HR', 'B4VR2HR', 'B4VU1HR') # old names
ecg_HR = c('hr1', 'hrM', 'hr3', 'hrS', 'hr5', 'hr6') # new names


## ECG quality 
# Translate ECG quality ratings to number format 
old = c('(1) EXCELLENT', '(2) GOOD', '(3) SCOREABLE', '(4) UNSCOREABLE', '(5) NO DATA')
new = c(1, 2, 3, 4, 5)
dfP4$B4VBEQn = varRecode(dfP4$B4VBEQ, old, new)  
dfP4$B4VMEQn = varRecode(dfP4$B4VMEQ, old, new)
dfP4$B4VPEQn = varRecode(dfP4$B4VPEQ, old, new)
dfP4$B4VSEQn = varRecode(dfP4$B4VSEQ, old, new)
dfP4$B4VR1EQn = varRecode(dfP4$B4VR1EQ, old, new) 
dfP4$B4VR2EQn = varRecode(dfP4$B4VR2EQ, old, new)
dfP4$B4VUEQn = varRecode(dfP4$B4VUEQ, old, new)

# c('B4VBEQ', 'B4VMEQ', 'B4VPEQ', 'B4VSEQ', 'B4VR1EQ', 'B4VR2EQ', 'B4VUEQ') # original names 
ecg_QO = c('B4VBEQn', 'B4VMEQn', 'B4VR1EQn', 'B4VSEQn', 'B4VR2EQn', 'B4VUEQn') # original names, in number format
ecg_Q = c('ecgQ1', 'ecgQM', 'ecgQ3', 'ecgQS', 'ecgQ5', 'ecgQ6') # new names 

## Miscellaneous variables to rename
#miscO = c('B1PGENDER'-DNE, 'B1PAGE_M2', 'B4ZAGE', 'B4ZB1PLG', 'B4ZB1SLG', 'B4ZB1CLG'-DNE THERE IS NO LAGP1 COG VARIABLE IN DATASET WILL ADJUST TO FIT B4ZB3CLG, 'B4QTA_AX', 'B4QCESD', 'B4H1I', 'B4PBMI', 'B4BIL6', 'B4BCRP')
#d[miscO]

miscO = c('B1PRSEX', 'B1PAGE_M2', 'B4ZAGE', 'B4ZB1PLG', 'B4ZB1SLG', 'B4ZB3CLG', 'B4QTA_AX', 'B4QCESD', 'B4H1I', 'B4PBMI', 'B4BIL6', 'B4BCRP')
misc = c('gender', 'P1_PIage', 'P4_age', 'months_P1PI_to_P4', 'months_P1SAQ_to_P4', 'months_P1cog_to_P4', 'P4_STAItrait', 'P4_CESD', 'P4_diabetes', 'P4_BMI', 'IL6', 'CRP')


## Remove whitespace from task variable values - there is no B4VTASK1 var, B4VCS1 and 2 are the psychological test variables where subjects mark the test completed. - no need to recode but will rename to keep according
#dfP4$B4VTASK1str = varRecode(dfP4$B4VTASK1, c("STROOP    ", "MATH      ", "INAPPLIC  ", "PASAT     "), c('STROOP', 'MATH', 'INAPPLIC', 'PASAT'))


dfP4$B4VTASK1str = dfP4$B4VCS1

dfP4$B4VCS1
dfP4$B4VCS2


View(dfP4)

## Rename variables with my intuitive names

setnames(dfP4, old=ecg_HRO, new=ecg_HR)
setnames(dfP4, old=ecg_QO, new=ecg_Q)
setnames(dfP4, old=miscO, new=misc)
setnames(dfP4, old=stressSRO, new=stressSR) #add




sort(names(dfP4))

sort(names(dfP4))[2400:2600]


View(dfP4)

# Check some quality ratings before removing any bad data
varDescribeBy(dfP4$hr1, dfP4$ecgQ1) # 1 = 742, 2 = 364, 3 = 47
varDescribeBy(dfP4$hrM, dfP4$ecgQM) # 1 = 667, 2 = 363, 3 = 66
varDescribeBy(dfP4$hr3, dfP4$ecgQ3) # 1 = 718, 2 = 365, 3 = 42
varDescribeBy(dfP4$hrS, dfP4$ecgQS) # 1 = 663, 2 = 374, 3 = 76
varDescribeBy(dfP4$hr5, dfP4$ecgQ5) # 1 = 698, 2 = 378, 3 = 43
varDescribeBy(dfP4$hr6, dfP4$ecgQ6) # 1 = 716, 2 = 345, 3 = 43 
count(is.na(dfP4$hr1)) # 102
count(is.na(dfP4$hrM)) # 159
count(is.na(dfP4$hr3)) # 130
count(is.na(dfP4$hrS)) # 142
count(is.na(dfP4$hr5)) # 136
count(is.na(dfP4$hr6)) # 151
```

```{r}
dfP4$stress1
dfP4$B4VTASK1str
dfP4$hr1
dfP4$ecgQ1
```



```{r}
#### Clean ECG Data ####

## Replace all ecg data that is not good (2) or excellent (1) with NA 
dfP4['hr1'][ (dfP4['ecgQ1'] != 1) & (dfP4['ecgQ1'] != 2) ] = NA
dfP4['hrM'][ (dfP4['ecgQM'] != 1) & (dfP4['ecgQM'] != 2) ] = NA
dfP4['hr3'][ (dfP4['ecgQ3'] != 1) & (dfP4['ecgQ3'] != 2) ] = NA
dfP4['hrS'][ (dfP4['ecgQS'] != 1) & (dfP4['ecgQS'] != 2) ] = NA
dfP4['hr5'][ (dfP4['ecgQ5'] != 1) & (dfP4['ecgQ5'] != 2) ] = NA
dfP4['hr6'][ (dfP4['ecgQ6'] != 1) & (dfP4['ecgQ6'] != 2) ] = NA

# How many removed? 
count(is.na(dfP4$hr1)) # 149 - 102 = 47
count(is.na(dfP4$hrM)) # 225 - 159 = 66
count(is.na(dfP4$hr3)) # 172 - 130 = 42
count(is.na(dfP4$hrS)) # 218 - 142 = 76
count(is.na(dfP4$hr5)) # 179 - 136 = 43
count(is.na(dfP4$hr6)) # 194 - 151 = 43

#### Clean diabetes data ####
dfP4$P4_diabetes = varRecode(dfP4$P4_diabetes, c("(1) YES", "(2) NO", "(3) BORDERLINE"), c(3, 1, 2)) # 1 = not diabetic, 2 = borderline diabetic, 3 = diabetic
dfP4$P4_diabetes = as.numeric(dfP4$P4_diabetes)
varDescribeBy(dfP4$M2ID, dfP4$P4_diabetes)


#### Score BMI data ####
# Underweight: BMI is less than 18.5
# Normal weight: BMI is 18.5 to 24.9
# Overweight: BMI is 25 to 29.9
# Obese: BMI is 30 or more
# via: https://www.cancer.org/cancer/cancer-causes/diet-physical-activity/body-weight-and-cancer-risk/adult-bmi.html
varDescribe(dfP4$P4_BMI)
# Exclude underweight
dfP4['P4_BMI'][ (dfP4['P4_BMI'] < 18.5 ) ] = NA

# Subset variables I want into a separate dataframe (dfP4ss) remove - 'B4VTASK1str' but kept psych test var "B4VCS1"
P4cols = c("M2ID", "M2FAMNUM", "SAMPLMAJ","B4VCS1","B4VCS2", misc, stressSR, ecg_HR, ecg_Q)
names(dfP4[P4cols])
dfP4ss = dfP4[P4cols]


#### Sort out order of stressor tasks ####
# ECG variables are tied to the task they were collected during/after, but tasks were counterbalanced. 
# Stress self-reports are tied to the order they were measured.
# I need heart rate in order measured, task irrelevant, so can look at relation to stress self-report.  
summary(dfP4ss$B4VTASK1str)

## Subset stroop-firsts and maths-firsts into 2 separate dataframes
# dS = stroop first
dS = subset(dfP4ss,"B4VCS1" == 'STROOP')
length(dS$M2ID) # 603

# dM = math first
dM = subset(dfP4ss, B4VTASK1str == 'MATH')
length(dM$M2ID) # 592

## Stroop first (stroop = 2, math = 4)
names(dS)[names(dS) == 'hrS'] = 'hr2'
names(dS)[names(dS) == 'hrM'] = 'hr4'
names(dS)[names(dS) == 'ecgQS'] = 'ecgQ2'
names(dS)[names(dS) == 'ecgQM'] = 'ecgQ4'

# Check did not edit other data frame like data.table sometimes does
names(dS)
names(dM) # good, still M and S

## Math first (math = 2, stroop = 4)
names(dM)[names(dM) == 'hrM'] = 'hr2'
names(dM)[names(dM) == 'hrS'] = 'hr4'
names(dM)[names(dM) == 'ecgQM'] = 'ecgQ2'
names(dM)[names(dM) == 'ecgQS'] = 'ecgQ4'

# Merge stroop-first and math-first dataframes back together
dfP4ss2 = merge.data.frame(dM, dS, all=TRUE)

# New ECG variable names with numbers instead of 's' or 'm'
ecg_Qn = c('ecgQ1', 'ecgQ2', 'ecgQ3', 'ecgQ4', 'ecgQ5', 'ecgQ6')
ecg_HRn = c('hr1', 'hr2', 'hr3', 'hr4', 'hr5', 'hr6')


#### Within-subj correlations between stress and heart rate ####
## Compute within subject stress x heart-rate correlation magnitudes and store as a variable
## Also plot each subjects stress and heart rate data individually (for QA) 

# Start a PDF file for the individual subject plots (X=stress, Y=heart rate)
pdf(paste(adir,"/coherence_hr_subjplots_",today,".pdf",sep=''))
# For each subject
for (s in dfP4ss2$M2ID) {
  print(s)
  # Subset and transpose subject's stress SRs and heart rate
  SUBstress = t(dfP4ss2[stressSR[1:5]][dfP4ss2$M2ID == s,])
  SUBhr = t(dfP4ss2[ecg_HRn[1:5]][dfP4ss2$M2ID == s,])
  # Put subjects stress and heart rate into their own dataframe
  SUBdf = data.frame(SUBstress, SUBhr)
  names(SUBdf)[1] = "stress"
  names(SUBdf)[2] = "hr"
  
  # Count number of NAs in stress self-reports
  cS = count((is.na(SUBdf$stress)))
  stressNotNA = as.numeric(cS[cS$x == 'FALSE',][2])
  
  # Count number of NAs in heart rate
  cH = count((is.na(SUBdf$hr)))
  hrNotNA = as.numeric(cH[cH$x == 'FALSE',][2])
  
  # Title for plot 
  tit = paste("Subject",s)
  
  # If there is at least 1 set of values (otherwise code bombs)
  if ( (!is.na(hrNotNA)) & (!is.na(stressNotNA)) ) {
    # Compute subject's stressSR x heart rate correlation
    SUBcor = cor(SUBdf, method="pearson", use="complete.obs")
    # Plot it 
    myplot = ggplot(SUBdf,aes(x=stress,y=hr))+
      geom_point(stat="identity",size=4.5, shape=1) +
      ggtitle(tit) +
      scale_x_continuous(name = "Self-reported stress", breaks = 1:10, limits = c(1,10)) +
      scale_y_continuous(name = "Heart rate", limits = c(40,130)) +
      theme_bw()+
      theme(panel.grid.minor = element_blank(), axis.text=element_text(size=14),
            axis.title=element_text(size=16), plot.title=element_text(size=16, hjust=.5)) +
      annotate("text", x=9.3, y=120, label = paste("r =",round(SUBcor[1,2],3)) ) # put correlation magnitude in plot
    print(myplot)
    # 
    dfP4ss2$coherence_as_r[dfP4ss2$M2ID==s] = as.numeric(SUBcor[1,2]) # add subject correlation magnitude to dataframe
    
    # Compute correlations only for subjects with all 5 timepoints 
    if ( (hrNotNA == 5) & (stressNotNA == 5) ) {
      SUBcor5 = cor(SUBdf, method="pearson", use="all.obs")
      dfP4ss2$coherence_as_r5[dfP4ss2$M2ID==s] = as.numeric(SUBcor5[1,2])
    }
    if ( (hrNotNA != 5) & (stressNotNA != 5) ) {
      dfP4ss2$coherence_as_r5[dfP4ss2$M2ID==s] = NA
    }
    
  }
  rm(SUBstress, SUBhr, SUBdf, SUBcor, SUBcor5, cS, cH, stressNotNA, hrNotNA, myplot) # clear variables before looping for next subject
}
dev.off() # Finish PDF with subject plots

# Check distribution
varDescribe(dfP4ss2$coherence_as_r) # n = 1036, mean = .49, sd = .47, median = .65, skew = -1.18, kurt = .54
hist(dfP4ss2$coherence_as_r, main='Coherence', xlab='Coherence (stress x HR correlation)', col='#1F618D', cex.axis=1.7, cex.main=1.6)
varDescribe(dfP4ss2$coherence_as_r5) # n = 944, mean = .5, sd = .46, median = .66, skew = -1.16, kurt = .46
hist(dfP4ss2$coherence_as_r5, main='Coherence - complete data only', xlab='Coherence (stress x HR correlation)', col='#1F618D', cex.axis=1.7, cex.main=1.6)
```

